### ISSUE TITLE
Implement function to update board based on user input 

### ISSUE THREAD

**Issue by corey-new** [corey-new/tic-tac-toe-game#4]
We want to update the board in `boardOptions` class, based on 2 parameters 
(space number input,  player's turn (`'X'` or `'O'`))

`newBoard()` could be nested in this function for printing, but `boardOptions` vector object would be needed to save updated board in memory.

**Comment by kearkyle** [comment]
Hey @corey-new, so I worked on the issue and made a commit on my fork here https://github.com/kearkyle/tic-tac-toe-game/commit/e62418dd1d1b2488b5c6709c00e7c300ffaaf1dd. Can you review and let me know if there's any other changes you want?

**Comment by kearkyle** [comment]
My newest commit https://github.com/kearkyle/tic-tac-toe-game/commit/b53346a1f9bfbd719ba8bd638e3b7713508a3842 fix the ASCII conversion for userInput from char to int.

**Comment by corey-new** [comment]
Hello @kearkyle, thanks for taking on this issue! Your changes seem to be working well, and ACII conversion is going to turn out very useful. Make sure to submit a pull request to the `dev-game` branch so I can solidify those changes :)

**Comment by kearkyle** [comment]
Hey @corey-new so I updated the code to keep the output format and also added an auto switch for every player's turn here https://github.com/kearkyle/tic-tac-toe-game/commit/b0989d14a48dec8c6582facf8ea080e25d058b6c. Is that the output format you want ?

**Comment by corey-new** [comment]
Yes this should work for now. Go ahead and submit a pull request whenever you're ready @kearkyle. Great work!
